@startuml
scale 350 width
[*] -> Ready: new/start()

state Ready {
}

state Running {
}


Ready --> Running: Resume
Running -d-> Ready: Suspend
Running -> BlockedWaiting: wait()/sleep()
BlockedWaiting -> Ready: event
Running -> [*]: terminate

state BlockedWaiting {
}


@enduml